language: python
dist: trusty
sudo: required
services:
- docker
before_install:
- sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty-backports universe'
- sudo apt-get update -qq
install:
- pip install https://github.com/ansible/ansible/archive/devel.tar.gz
- pip install -e git+https://github.com/ansible/ansible-container.git@develop#egg=ansible_container[docker]
script:
- docker version
- docker-compose version
- docker info
- cd test
- mkdir demo
- cd demo
- ansible-container init ansible.django-gulp-nginx
- cp -R ../../src/* src
- cp -R ../../project/* project
- ansible-container build
- ansible-container run -d
- docker ps -a
- docker images
- cd ..
- ansible-playbook -i inventory test.yml
- cd demo
- ansible-container stop -f
notifications:
  email: false
  slack:
    rooms:
      secure: IvdJAMzZUQgyzUt1a2VaQDPAisAX04O9tc+lbdrHx9OI92XiLtQgPrtPjytsHULKUGKDtaQ7pqorUVJviz7biO5crzLo1mct6WuWvJgU7V0BEvHXH2Ip+KVCPDhvjrVcu7NMY9JxZ+HZSszHQgGaLttg+GzxhoBqiHA/G6Ien+MEYgU8cu8EMxsSxNhJ5CGfwnGKA2yVM9T1E/2ZaE+zAUMHSnuG86jCW3m7gbufgxaDDGs2rdWLSQHCE6BwmRdgg3/SWpX1F7dMNcGT9Elru06QHdxRI316WRrm6q0mGQgIr0+orDHM9lEbzC2R32TK5i7BMSnM1ngDTAw8utt03iw+LbtDRIbJDg9oxBPdfg4DBoTuNJe3pjCta9btGUH5WEY0hVbMGjVQudF/Rct0vxgijRt0yKFE9ej87gTVQ2TyMrygXjJVSZYuDIgEM3sqtMJvBSglwzFBrntm+RkrR/PzqW6ZMpnqlIC+ejPdScEUw6RidyJcOWOWp02AuNA/nAIeYJ0+s6AnlP3DT9btpjsui5LP8N21QQiYh3utOoPIGmNxH9QJZkYZ1qYu4P2GjkZj8Ig8y/cJ9YXyKEKVkYzY+XQrGDpxWhYmm05wfKWEg4pISTl69OwdC8FfyoQNdKL9arkOwWEzCYWkcRfdhiezQP6QGlQuuH5YNsOW54g=
    on_success: change
    on_failure: always
